# Example of .secrets.toml file
[default]
# Django secrets
SECRET_KEY = ''
# Secrets keys
OPENWEATHER_API_KEY = 'Your openweather api key'
# db
DATABASES__default__USER = ''
DATABASES__default__PASSWORD = ''
DATABASES__default__NAME = ''
DATABASES__default__HOST = ''
DATABASES__default__PORT = ''
