# File for settings the default backend
[default]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
ALLOWED_HOSTS = ['*']
STATIC_URL = '/static/'
USE_I18N = true
USE_TZ = true
DEBUG = true
GEC_URL = 'http://api.openweathermap.org/geo/1.0/direct?'
WEATHER_URL = 'https://api.open-meteo.com/v1/forecast?latitude'
